force-app/main/default/objects/OpportunityProductLineItem__c/OpportunityProductLineItem__c.object-meta.xml
<CustomObject>
    <label>商机产品</label>
    <nameField>
        <displayFormat>OPL-{000000}</displayFormat>
        <label>商机产品编号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OpportunityProductLineItem__c/fields/Factory__c.field-meta.xml
<CustomField>
    <fullName>Factory__c</fullName>
    <label>工厂</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CCEC</fullName>
                <default>true</default>
                <label>CCEC</label>
            </value>
            <value>
                <fullName>DCEC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityProductLineItem__c/fields/OpportunityName__c.field-meta.xml
<CustomField>
    <fullName>OpportunityName__c</fullName>
    <label>项目名称</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>商机产品</relationshipLabel>
    <relationshipName>OpportunityProductmtpz</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OpportunityProductLineItem__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>型号</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>商机产品</relationshipLabel>
    <relationshipName>OpportunityProduct3XV0</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Factory__c.field-meta.xml
<CustomField>
    <fullName>Factory__c</fullName>
    <label>工厂</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CCEC</fullName>
            </value>
            <value>
                <fullName>DCEC</fullName>
            </value>
            <value>
                <fullName>RMEP</fullName>
            </value>
            <value>
                <fullName>DAV</fullName>
            </value>
            <value>
                <fullName>SEP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SimilarProject__c/SimilarProject__c.object-meta.xml
<CustomObject>
    <label>相似项目</label>
    <nameField>
        <displayFormat>SP-{000000}</displayFormat>
        <label>相似项目</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SimilarProject__c/fields/Factory__c.field-meta.xml
<CustomField>
    <fullName>Factory__c</fullName>
    <label>工厂</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CCEC</fullName>
            </value>
            <value>
                <fullName>DCEC</fullName>
            </value>
            <value>
                <fullName>RMEP</fullName>
            </value>
            <value>
                <fullName>DAV</fullName>
            </value>
            <value>
                <fullName>SEP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SimilarProject__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>机型</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>相似项目</relationshipLabel>
    <relationshipName>SimilarProduct3Xnz</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SimilarProject__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>项目</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>相似项目</relationshipLabel>
    <relationshipName>SimilarProjectnF78</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SimilarProject__c/fields/SimilarProjectGroup__c.field-meta.xml
<CustomField>
    <fullName>SimilarProjectGroup__c</fullName>
    <label>相似项目组</label>
    <referenceTo>SimilarProjectGroup__c</referenceTo>
    <relationshipLabel>相似项目</relationshipLabel>
    <relationshipName>SimilarProjectQMBc</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SimilarProjectGroup__c/SimilarProjectGroup__c.object-meta.xml
<CustomObject>
    <label>相似项目组</label>
    <nameField>
        <label>相似项目组名称</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SimilarProjectGroup__c/fields/SimilarType__c.field-meta.xml
<CustomField>
    <fullName>SimilarType__c</fullName>
    <label>相似类型</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>项目名称</fullName>
            </value>
            <value>
                <fullName>设计院/工厂/机型</fullName>
            </value>
            <value>
                <fullName>船厂/工厂/机型</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PSBU_ProjectSimilarHandleBL.cls
/**
* Company : DCIT
* Description : *
* This class 
*
*************************************************************************************
***
* History :
* [26.Sep.2019] Jones Yang - Code Creation */

public with sharing class PSBU_ProjectSimilarHandleBL {

    public PSBU_ProjectSimilarHandleBL() {
    }

    //
    private map<string, string> getAccountName( List<Account> listAccount ) {
        map<string, string> mapAccountName = new map<string, string>();
        for(Account acc : listAccount){
            mapAccountName.put(acc.Id, acc.Name);
        }
        return mapAccountName;
    }

    //
    public void handleDesigningInstituteCondition () {
        if( !PSBU_ProjectDML.getDesigningInstituteOppProductsAgg().isEmpty() && !PSBU_ProjectDML.getDesigningInstituteOppProducts().isEmpty() ){
            //map<string, OpportunityProductLineItem__c> mapOppProductLines = new map<string, OpportunityProductLineItem__c>();        
            List<SimilarProjectGroup__c> listSimilarProGroup = new List<SimilarProjectGroup__c>();
            for( AggregateResult ar : PSBU_ProjectDML.getDesigningInstituteOppProductsAgg() ) {
                if( integer.valueof(ar.get('expr0')) > 1 ) {
                    SimilarProjectGroup__c objSimilarProGroup = new SimilarProjectGroup__c();
                    objSimilarProGroup.Name = getAccountName(PSBU_ProjectDML.getAccounts()).get(string.valueof(ar.get('OpportunityName__r.DesigningInstitute__c'))) + string.valueof(ar.get('Factory__c')) + string.valueof(ar.get('Product__r.Name'));
                    objSimilarProGroup.SimilarType__c = '设计院/工厂/机型';
                    listSimilarProGroup.add(objSimilarProGroup);
                }
            }

            try {
                insert listSimilarProGroup;
            } catch(DmlException e) {
                System.debug('The following exception has occurred: ' + e.getMessage());
            }

            List<SimilarProject__c> listSimilarPros = new List<SimilarProject__c>();
            for( SimilarProjectGroup__c spg : listSimilarProGroup) {   
                for(OpportunityProductLineItem__c opli : PSBU_ProjectDML.getDesigningInstituteOppProducts() ){
                    SimilarProject__c objSimilarPro = new SimilarProject__c();
                    string sGroupNamePro = getAccountName(PSBU_ProjectDML.getAccounts()).get(opli.OpportunityName__r.DesigningInstitute__c) + opli.Factory__c + opli.Product__r.Name;
                    if( spg.Name == sGroupNamePro ){
                        objSimilarPro.SimilarProjectGroup__c = spg.Id;
                        objSimilarPro.Project__c = opli.OpportunityName__c;
                        listSimilarPros.add(objSimilarPro);
                    }
                }
            }

            try {
                insert listSimilarPros;
            } catch(DmlException e) {
                System.debug('The following exception has occurred: ' + e.getMessage());
            }
        }

    }

    //
    public void handleShipyardCondition () {
        
    }
}