force-app/main/default/objects/OpportunityProductLineItem__c/OpportunityProductLineItem__c.object-meta.xml
<CustomObject>
    <label>商机产品</label>
    <nameField>
        <displayFormat>OPL-{000000}</displayFormat>
        <label>商机产品编号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OpportunityProductLineItem__c/fields/Factory__c.field-meta.xml
<CustomField>
    <fullName>Factory__c</fullName>
    <label>工厂</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CCEC</fullName>
                <default>true</default>
                <label>CCEC</label>
            </value>
            <value>
                <fullName>DCEC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityProductLineItem__c/fields/OpportunityName__c.field-meta.xml
<CustomField>
    <fullName>OpportunityName__c</fullName>
    <label>项目名称</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>商机产品</relationshipLabel>
    <relationshipName>OpportunityProductmtpz</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OpportunityProductLineItem__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>型号</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>商机产品</relationshipLabel>
    <relationshipName>OpportunityProduct3XV0</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityProductLineItem__c/fields/ProjectNameConflictCondition__c.field-meta.xml
<CustomField>
    <fullName>ProjectNameConflictCondition__c</fullName>
    <formula>LEN( OpportunityName__c ) &gt;= 6</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>项目名称冲突条件</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Factory__c.field-meta.xml
<CustomField>
    <fullName>Factory__c</fullName>
    <label>工厂</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CCEC</fullName>
            </value>
            <value>
                <fullName>DCEC</fullName>
            </value>
            <value>
                <fullName>RMEP</fullName>
            </value>
            <value>
                <fullName>DAV</fullName>
            </value>
            <value>
                <fullName>SEP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PSBU_ProjectDML.cls
/**
* Company : DCIT
* Description : *
* This class 
*
*************************************************************************************
***
* History :
* [26.Sep.2019] Jones Yang - Code Creation */

public with sharing class PSBU_ProjectDML {
    
    public PSBU_ProjectDML() {
    }


    //find all account name.
    public static List<Account> getAccounts(){    
        List<Account> listAcccounts = [select Id, Name from Account ];
        return listAcccounts;
    }

    //Description: similar project group condition, rule include opportuinty Designing Institute, factory and Product, return group list data.
    public static List<AggregateResult> getDesigningInstituteOppProductsAgg(){    
        List<AggregateResult> groupedResults = [select count(Id), Factory__c, Product__r.Name,OpportunityName__r.DesigningInstitute__c
        from OpportunityProductLineItem__c where OpportunityName__r.DesigningInstitute__c != null and OpportunityName__r.SimilarProjectCondition__c =: true group by Factory__c,Product__r.Name,OpportunityName__r.DesigningInstitute__c];
        return groupedResults;
    }

    //Description: simalar group condition 
    public static List<OpportunityProductLineItem__c> getDesigningInstituteOppProducts(){    
        List<OpportunityProductLineItem__c> listOppProductItems = [select Id, Factory__c, Product__r.Name,OpportunityName__r.DesigningInstitute__c, OpportunityName__c 
        from OpportunityProductLineItem__c where OpportunityName__r.DesigningInstitute__c != null and OpportunityName__r.SimilarProjectCondition__c =: true ];
        return listOppProductItems;
    }

    //Description: similar project group condition, rule include opportuinty shipyard, factory and Product, return group list data.
    public static List<AggregateResult> getShipyardOppProductsAgg(){    
        List<AggregateResult> groupedResults = [select count(Id), Factory__c, Product__r.Name,OpportunityName__r.Shipyard__c 
        from OpportunityProductLineItem__c where OpportunityName__r.Shipyard__c != null and OpportunityName__r.SimilarProjectCondition__c =: true group by Factory__c,Product__r.Name,OpportunityName__r.Shipyard__c];
        return groupedResults;
    }

    //
    public static List<OpportunityProductLineItem__c> getShipyardOppProducts(){    
        List<OpportunityProductLineItem__c> listOppProductItems = [select Id, Factory__c, Product__r.Name,OpportunityName__r.Shipyard__c, OpportunityName__c 
        from OpportunityProductLineItem__c where OpportunityName__r.Shipyard__c != null and OpportunityName__r.SimilarProjectCondition__c =: true ];
        return listOppProductItems;
    }    

    //find all project name length are more than 6, and similar project condition.
    public static List<Opportunity> getOppName(){    
        List<Opportunity> listOppProjectName = [select Id, Name from Opportunity where SimilarProjectCondition__c =: true and ProjectNameConflictCondition__c =: true ];
        return listOppProjectName;
    }     
}